### ISSUE TITLE
Pause implementation

### ISSUE THREAD

**Issue by Patitotective** [define-private-public/stopwatch#10]
I'm using this library for a stopwatch application, therefore I need a way to "pause" the stopwatch without saving a lap.
The only way I've found to achieve this is to set `stopwatch.recordLaps` to false before `stopwatch.stop()` (needed to make `recordLaps` field public in `stopwatch/regular.nim`)
```nim
...
sw.recordLaps = false
sw.stop()
sw.recordLaps = true
```

**Comment by Patitotective** [comment]
Another way would be to remove the created lap after `sw.stop()`, but if I use `sw.rmLap()` it will also subtract the lap from the total, and I don't want that

**Comment by define-private-public** [comment]
Closing since fix was merged in #11
