### ISSUE TITLE
running total

### ISSUE THREAD

**Issue by eagle-provision** [define-private-public/stopwatch#2]
Would be nice if we had a way to get the running total without having to foldl the whole array.

**Comment by define-private-public** [comment]
Do you mean the line right here: https://github.com/define-private-public/stopwatch/blob/master/stopwatch.nim#L274

I think some sort of accumulator member in the `Stopwatch` object may be able to do that.  I'd like to get your opinion before making the change.

**Comment by eagle-provision** [comment]
Yes, that's the line and the member accumulator is what I had in mind.

Also, would be nice if we had a way to disable the laps counting when it's not needed so as not to leak memory (perhaps change initialization and test for laps == nil, the other ways I can think of are either with passing parameters or yet another member variable)

**Comment by define-private-public** [comment]
Alright it uses an accumulator now to store total time.

Please open up a new issue to discuss the non-recording of laps.
