### ISSUE TITLE
non-recording of laps

### ISSUE THREAD

**Issue by eagle-provision** [define-private-public/stopwatch#3]
Would be nice if there was a way to disable them.

ideas: change initialization and test for laps == nil, pass parameters or add yet another member variable.

**Comment by define-private-public** [comment]
This looks like it may be a little more work.  After the `epochTimes()` fork has been tested (and possibly merged) I'll tackle this.

**Comment by define-private-public** [comment]
Sorry for the delayed work on this.  It's going to be more like a week before I can start on it.

**Comment by define-private-public** [comment]
Alright, starting work on this.

**Comment by define-private-public** [comment]
Okay, the changes are in the `no_lap_recording` branch.  Pull it and run two tests for me.  Once with `tester` by itself, then another time, but passing in the `nolap` argument.  Make sure they look similar to that from `master`, except well, for no laps.

These were my results on Linux:

`./tester`:
```
Testing with laps on.
laps=@[]
total=0.0
laps=@[0]
total=1.000101
1.000141
total=1.000141

total=1.50021
0.500093
0.500101
total=1.500242

0.0
0.100073
0.100093
0.100099
total=1.600346
lapCount=2
lapCount=3
0.100115
0.100124
0.200205
total=1.700447

lapCount=3
L1=1.000141
L2=0.500101
all laps=@[500101000, 200205000]
lapCount=2
----
lapCount=3
all laps(s)=@[1.000141, 0.500101, 0.200205]

lapCount=0
total=0.010071
total=1e-06
total(s)=0.250081
total(m)=250
total(u)=250110
total(n)=250113000

bench(sleep(1000))=1.00008
```

`./tester nolap`:
```
Testing with laps off.
laps=nil
total=0.0
laps=nil
total=1.00008
1.000106
total=1.000106

total=1.500176
0.500108
0.500116
total=1.500222

0.0
0.100075
0.100111
0.100117
total=1.600343
lapCount=0
lapCount=0
0.100143
0.100149
0.200243
total=1.700465

lapCount=0
L1=0.0
L2=0.0
all laps=nil
lapCount=0
----
lapCount=0
all laps(s)=nil

lapCount=0
total=0.010069
total=1e-06
total(s)=0.250089
total(m)=250
total(u)=250119
total(n)=250121000

bench(sleep(1000))=1.00007
```

Results were similar on OS X.  Accumulated time is still recorded though.

Do the return values look okay to you if lapping is off (e.g. `proc laps()` will return a `nil`, `proc lap()` will always return 0)?

**Comment by eagle-provision** [comment]
All looks fine under linux. Should I really test in wine and windows? (did anything that depends on architecture change?)

As for the nil, perhaps it's better to return a @[] so users don't accidentally hit a null pointer.

**Comment by define-private-public** [comment]
I like to be paranoid.  I was thinking about doing the empty seq as well.  I'll get the change in.

**Comment by define-private-public** [comment]
Alright, pushed.  Before I go an close this issue, do you think there might be any issues for those who use JavaScript as a target instead of C?

**Comment by eagle-provision** [comment]
I just tested it and `system/timers` doesn't work with javascript, but `times`'s epochTime does. Didn't test the precision but it's not as easy to test because the javascript target lacks the `os` module where `sleep` is from.

**Comment by define-private-public** [comment]
Okay, Ill got make a new issue to add JS support.  We'll just ignore the sleep thing for now, or add a JS tester.
