### ISSUE TITLE
Add JavaScript target support

### ISSUE THREAD

**Issue by define-private-public** [define-private-public/stopwatch#8]
`getTicks()` doesn't work in JS (from `system/timers`) but reportedly `epochTime()` does (like OS X).  Test this and add it in.

**Comment by define-private-public** [comment]
Done!

**Comment by eagle-provision** [comment]
works.

**Comment by eagle-provision** [comment]
precision turns out to be very bad.

```
import stopwatch

var sw = stopwatch(false)
sw.start()
while sw.totalSecs < 0.987654321:
  discard
sw.stop()

echo sw.totalSecs - 0.987654321
```
linux: 6.790000000537881e-007
js: 0.00034567900000004315

**Comment by define-private-public** [comment]
It's not the best, but it is something.  I've already merged it in.

Is there maybe some native JS function we could use instead?  I'm not a fan of JS, I only write it when I need to, though I thought it would be good to add support.

**Comment by eagle-provision** [comment]
My exposure to JS is close to zero, not a fan either.

A quick search turned up the now() function [here](http://stackoverflow.com/questions/6233927/microsecond-timing-in-javascript#21120901), note the answer is from '14. Not sure how to call it from nim though.

**Comment by define-private-public** [comment]
It's actually not that difficult.  I'm working on a <canvas> tag wrapper at the moment: https://gitlab.com/define-private-public/HTML5-Canvas-Nim

I'll see into this once I'm done with that thing above.
